server:
  port: 8001

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /status
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
